### ISSUE TITLE
what is the masks .h5 file， how can i download it and run your code

### ISSUE THREAD

**Issue by lvguofeng1303** [mirzaevinom/data_science_bowl_2018#1]
Thank you for making your code public and let me learn.
but i download your code and follow your Instruction，i met some issues
when i run 

> python augment_preprocess.py

i met some issues:

Traceback (most recent call last):
  File "augment_preprocess.py", line 473, in <module>
    make_n_save_mosaic()
  File "augment_preprocess.py", line 361, in make_n_save_mosaic
    with h5py.File(path, "r") as hf:
  File "/home/lgf/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/lgf/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '../data/stage1_train/ad473063dab4bf4f2461d9a99a9c0166d4871f156516d9e0a523484e7cf2258d/masks/ad473063dab4bf4f2461d9a99a9c0166d4871f156516d9e0a523484e7cf2258d.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

i want know what is this .h5 file

And i want to skip preprocess, and run 

> python train.py

i met some issues again:

Traceback (most recent call last):
  File "train.py", line 128, in <module>
    train_path, seed=11, test_size=0.1)
  File "train.py", line 100, in train_validation_split
    df = pd.read_csv('../data/classes.csv')
  File "/home/lgf/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/lgf/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/lgf/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/home/lgf/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/lgf/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'../data/classes.csv' does not exist

 I can't run again because I don't have a .csv.

**Comment by mirzaevinom** [comment]
Hi @lvguofeng1303, Glad you find this repo helpful. 
Just added the required files for running `augment_preprocess.py` and `train.py`. Try pulling the repo again. 
I am not sure why you are having `h5py` issue. I create `.h5` files for each mask by running `augment_preprocess.py`. This makes reading mask files a little bit faster. However, the code should still run without those files since I have `if os.path.exists(path):` statement in `train.py`.

Hope it works!

**Comment by lvguofeng1303** [comment]
Hi @mirzaevinom , thank for your help.
i find `augment_preprocess.py` have a  function `data_to_array()`   which is to save masks  as h5 files to make trainig faster as you say. 
so i change the `__main()__` sequence,  the function `preprocess_external_data,  make_n_save_mosaic()`  run after `data_to_array()`, i think you can change the code sequence.
beacuse i think maybe have too many people like me  just download train_data and dont konw create .h5file before run this `python augment_preprocess.py` 
At last, thank for your code, i learn too many.  this is my run result
skip augment, i got the LB score 0.551
after augment, i got the LB score 0.585 (all my result the configurations  IMAGE_MIN_DIM/IMAGE_MAX_DIM=256,  if 512 i have the problem that memory exceed, and i dont know why)

**Comment by mirzaevinom** [comment]
Glad you learned from my scripts! You got pretty close to my results even with 256x256x3. As for the memory problem, I think you might have a smaller memory on your GPU. I have tested it on 16 GB GPUs.
